name: Crowdin Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
