name: Crowdin Action

on:
  push:
    branches: [ l10n-to-crowdin ]
  schedule:
    - cron: "*/1 * * * *"

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.16
      with:
        crowdin_branch_name: l10n-to-crowdin
        pull_request_base_branch_name: l10n-to-crowdin
        localization_branch_name: l10n-from-crowdin
        upload_translations: false
        download_translations: true
        skip_untranslated_strings: false
        export_only_approved: false
        import_eq_suggestions: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
